### ISSUE TITLE
Why use this? Just curious!

### ISSUE THREAD

**Issue by ceesvanegmond** [silvanverschuur/esp-p1-mqtt#2]
Hi @silvanverschuur ,

I was stroling around the HASSIO forums and saw your post regarding this repo.
I'm' wondering why you want this device between your hassio instance.

Is it because the many state-event changes in hassio when using the dsmr component? To bundle it every 30 seconds instead of every second?

**Comment by silvanverschuur** [comment]
@ceesvanegmond You need some hardware to get the information from your smart meter into Home Assistant. If you run Home Assistant on a Raspberry Pi (near your smart meter) you can use a simple USB/serial cable that inverts the signal of the smart meter. 

I my case my server (PC) running Home Assistant is not located near the smart meter. Using an ESP device it's possible to have a really small hardware device near the smart meter that read/parses the messages and publishes them to my MQTT server.

I could have used a Pi for this but that's more expensive, needs a separate power supply and is less reliable (SD card).

Another advantage is that you can buffer information into the ESP to reduce the amount of sensor changes in HA as you already mentioned.

Besides Home Assistant reading MQTT messages, I'm running a script on my server that subscribes to the same MQTT topic and sends the information to a MySQL database. I'm using that database for long time history and aggregation of daily/monthly/yearly summaries. It also combines data from my solar system so I have a complete overview of my whole energy consumption/production.
