### ISSUE TITLE
Elco

### ISSUE THREAD

**Issue by Remicade** [silvanverschuur/esp-p1-mqtt#3]
Hi Silvan,
I have been looking at the pics and want to check something.
Is the elco placed only between 5 volt and ground?
It is not drawn in your scheme.
Probably as a buffer for the sending which consumes some power?
Thanks in advance,
Paul

**Comment by silvanverschuur** [comment]
@Remicade I've uploaded some photos of the board on the Home Assistant forum in the past. You can find them [here](https://community.home-assistant.io/t/support-for-dutch-smart-meter/240582/66).
