### ISSUE TITLE
Twice  a function with the same name

### ISSUE THREAD

**Issue by horemansp** [silvanverschuur/esp-p1-mqtt#4]
Hi Silvan, 
Many thanks for this. I was struggling with the serial read and this is really helpful.
When looking at your code for the MQTT part I noticed it has a function that has two implementations. I'm quite new to C++ and maybe it is possible but then my question is how does this work?

from your P1_mqtt.h:
`boolean publishMqtt(const char *topic, float value, int precision) {
  char buffer[VALUE_LENGTH];
  return mqttClient.publish(topic, ftoa(buffer, value, VALUE_LENGTH, precision), true);
}

boolean publishMqtt(const char *topic, int value) {
  char buffer[VALUE_LENGTH];
  return mqttClient.publish(topic, itoa(value, buffer, VALUE_LENGTH), true);
}`

**Comment by silvanverschuur** [comment]
The difference between the two functions is that the first one is used for floating point values and the second one for integers. The floating point variant is also used to format the value with a given precision.

For example, the voltage from the P1 meter could be something like 239.23190. I'm using the first function to convert this floating point value into a number with 1 decimal (239.2). It converts the value to a string and publishes it to the MQTT topic.

The function with the integer as parameter, just converts the value to a string and publishes it to the MQTT topic.
